# Generated by Django 4.0.4 on 2022-04-18 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_public_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='public',
        ),
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
