# Generated by Django 4.0.4 on 2022-04-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_public_task_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='public',
        ),
    ]
