# Generated by Django 4.0.4 on 2022-04-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
